version: 0.2

phases:
  install:
    runtime-versions:
        nodejs: 12
    commands:
        - echo Installing source NPM dependencies...
        - cd src/ui && npm install
        - cd src/UI && npm install -g @angular/cli
  build:
    commands:
        - echo Build started 
        - cd src/ui && ng build --prod
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes