version: 0.2

env:
  variables:
    UI_PROJECT_PATH: "src/ui"
phases:
  install:
    runtime-versions:
        nodejs: 12
    commands:
        - echo Installing source NPM dependencies...
        - cd $UI_PROJECT_PATH
        - npm install
        - npm install -g @angular/cli
  build:
    commands:
        - echo Build started 
        - cd $UI_PROJECT_PATH
        - ng build --prod
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes