AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  book-list

  SAM Template for Book List API

Parameters:
  DynamoDbRegion:
    Type: String
    Default: local
  DynamoDbEndpoint:
    Type: String
    Default: "http://localhost:8000"
  CorsAllowedOrigins:
    Type: String
    Default: "'http://localhost:4200'"
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60
    Tracing: Active
    Environment:
      Variables:
        DYNAMODB_TABLE_NAME: !Ref BooksTable
        DYNAMODB_REGION: !Ref DynamoDbRegion
        DYNAMODB_ENDPOINT: !Ref DynamoDbEndpoint
        CORS_ALLOWED_ORIGINS: !Ref CorsAllowedOrigins
  Api:
    Cors:
      AllowMethods: "'OPTIONS,GET,POST,PUT,DELETE'"
      AllowHeaders: "'Content-Type'"
      AllowOrigin: !Ref CorsAllowedOrigins

Resources:
  BookListApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        ApiKeyRequired: true

  BookList:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: layers/booklist
      Handler: dummy.lambda_handler
      Runtime: python3.8
  
  BookListLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: BookListLayer
      Description: Layer with shared code for Books API
      ContentUri: ./.aws-sam/build/Booklist
      CompatibleRuntimes:
        - python3.8
      RetentionPolicy: Delete
    DependsOn: 
      - BookList

  GetBooksFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/get_books/
      Handler: app.lambda_handler
      Runtime: python3.8
      Policies: 
        - DynamoDBReadPolicy:
            TableName: !Ref BooksTable
      Layers:
        - !Ref BookListLayer
      Events:
        GetBooks:
          Type: Api
          Properties:
            RestApiId: !Ref BookListApi
            Path: /api/books
            Method: get

  SearchBooksFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/search_books/
      Handler: app.lambda_handler
      Runtime: python3.8
      Layers:
        - !Ref BookListLayer
      Events:
        GetBooks:
          Type: Api
          Properties:
            RestApiId: !Ref BookListApi
            Path: /api/books/search
            Method: get

  PostBookFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/post_book/
      Handler: app.lambda_handler
      Runtime: python3.8
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref BooksTable
      Layers:
        - !Ref BookListLayer
      Events:
        PostBook:
          Type: Api
          Properties:
            RestApiId: !Ref BookListApi
            Path: /api/books
            Method: post

  PutBookFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/post_book/
      Handler: app.lambda_handler
      Runtime: python3.8
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref BooksTable
      Layers:
        - !Ref BookListLayer
      Events:
        PutBook:
          Type: Api
          Properties:
            RestApiId: !Ref BookListApi
            Path: /api/books/{isbn}
            Method: put

  DeleteBookFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/delete_book/
      Handler: app.lambda_handler
      Runtime: python3.8
      Policies: 
        - DynamoDBCrudPolicy:
            TableName: !Ref BooksTable
      Layers:
        - !Ref BookListLayer
      Events:
        DeleteBook:
          Type: Api
          Properties:
            RestApiId: !Ref BookListApi
            Path: /api/books/{isbn}
            Method: delete

  BooksTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "Books"
      AttributeDefinitions:
        - 
          AttributeName: "isbn"
          AttributeType: "S"
      KeySchema:
        - 
          AttributeName: "isbn"
          KeyType: "HASH"
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      Tags:
        - Key: app
          Value: book-list